"""Initial migration

Revision ID: 13bf03f5c6f6
Revises:
Create Date: 2026-02-05 11:06:54.689975

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "13bf03f5c6f6"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "build_kits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("groupset", sa.String(), nullable=True),
        sa.Column("wheelset", sa.String(), nullable=True),
        sa.Column("cockpit", sa.String(), nullable=True),
        sa.Column("tires", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "geometry_data",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("size_label", sa.String(), nullable=False),
        sa.Column("stack", sa.Integer(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=False),
        sa.Column("top_tube_effective_length", sa.Integer(), nullable=False),
        sa.Column("seat_tube_length", sa.Integer(), nullable=False),
        sa.Column("head_tube_length", sa.Integer(), nullable=False),
        sa.Column("chainstay_length", sa.Integer(), nullable=False),
        sa.Column("head_tube_angle", sa.Float(), nullable=False),
        sa.Column("seat_tube_angle", sa.Float(), nullable=False),
        sa.Column("bb_drop", sa.Integer(), nullable=False),
        sa.Column("wheelbase", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "framesets",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("material", sa.String(), nullable=True),
        sa.Column("geometry_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geometry_id"],
            ["geometry_data.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "bike_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("frameset_id", sa.Integer(), nullable=False),
        sa.Column("build_kit_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["build_kit_id"],
            ["build_kits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["frameset_id"],
            ["framesets.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bike_products")
    op.drop_table("framesets")
    op.drop_table("geometry_data")
    op.drop_table("build_kits")
    # ### end Alembic commands ###
