"""add frameset category

Revision ID: 991031c52543
Revises: c1b480bb574e
Create Date: 2026-02-06 11:53:54.951378

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "991031c52543"
down_revision: str | Sequence[str] | None = "c1b480bb574e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("framesets", sa.Column("category", sa.String(), server_default="other", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("framesets", "category")
    # ### end Alembic commands ###
