"""update_unique_key

Revision ID: 9f40e69e09fb
Revises: b8641691a825
Create Date: 2026-02-18 12:27:45.172623

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f40e69e09fb"
down_revision: str | Sequence[str] | None = "b8641691a825"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("_brand_model_uc"), "bike_definitions", type_="unique")
    op.create_unique_constraint(
        "_brand_model_uc",
        "bike_definitions",
        ["brand_name", "model_name", "year_start", "year_end"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_brand_model_uc", "bike_definitions", type_="unique")
    op.create_unique_constraint(
        op.f("_brand_model_uc"),
        "bike_definitions",
        ["brand_name", "model_name"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
