"""initial

Revision ID: b3b1fc3d67ef
Revises:
Create Date: 2026-02-09 22:45:11.107119

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3b1fc3d67ef"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bike_families",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sa.String(length=255), nullable=False),
        sa.Column("family_name", sa.String(length=255), nullable=False),
        sa.Column("category", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_name", "family_name", name="_brand_family_uc"),
    )
    op.create_index(op.f("ix_bike_families_brand_name"), "bike_families", ["brand_name"], unique=False)
    op.create_table(
        "build_kits",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("groupset", sa.String(), nullable=True),
        sa.Column("wheelset", sa.String(), nullable=True),
        sa.Column("cockpit", sa.String(), nullable=True),
        sa.Column("tires", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "frame_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("family_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("year_start", sa.Integer(), nullable=True),
        sa.Column("year_end", sa.Integer(), nullable=True),
        sa.Column("material", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["family_id"], ["bike_families.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "geometry_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("definition_id", sa.Integer(), nullable=False),
        sa.Column("size_label", sa.String(length=20), nullable=False),
        sa.Column("stack_mm", sa.Integer(), nullable=False),
        sa.Column("reach_mm", sa.Integer(), nullable=False),
        sa.Column("top_tube_effective_mm", sa.Integer(), nullable=True),
        sa.Column("seat_tube_length_mm", sa.Integer(), nullable=True),
        sa.Column("head_tube_length_mm", sa.Integer(), nullable=True),
        sa.Column("head_tube_angle", sa.Float(), nullable=False),
        sa.Column("seat_tube_angle", sa.Float(), nullable=False),
        sa.Column("chainstay_length_mm", sa.Integer(), nullable=False),
        sa.Column("wheelbase_mm", sa.Integer(), nullable=False),
        sa.Column("bb_drop_mm", sa.Integer(), nullable=False),
        sa.Column("fork_offset_mm", sa.Integer(), nullable=True),
        sa.Column("trail_mm", sa.Integer(), nullable=True),
        sa.Column("standover_height_mm", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["definition_id"], ["frame_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("definition_id", "size_label", name="_def_size_uc"),
    )
    op.create_index(op.f("ix_geometry_specs_reach_mm"), "geometry_specs", ["reach_mm"], unique=False)
    op.create_index(op.f("ix_geometry_specs_stack_mm"), "geometry_specs", ["stack_mm"], unique=False)
    op.create_table(
        "bike_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sku", sa.String(), nullable=False),
        sa.Column("colors", sa.JSON(), server_default="[]", nullable=False),
        sa.Column("geometry_spec_id", sa.Integer(), nullable=False),
        sa.Column("build_kit_id", sa.Integer(), nullable=False),
        sa.Column("source_url", sa.String(length=1024), nullable=True),
        sa.ForeignKeyConstraint(["build_kit_id"], ["build_kits.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["geometry_spec_id"], ["geometry_specs.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("geometry_spec_id", "build_kit_id", name="_geo_bk_uc"),
        sa.UniqueConstraint("sku"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bike_products")
    op.drop_index(op.f("ix_geometry_specs_stack_mm"), table_name="geometry_specs")
    op.drop_index(op.f("ix_geometry_specs_reach_mm"), table_name="geometry_specs")
    op.drop_table("geometry_specs")
    op.drop_table("frame_definitions")
    op.drop_table("build_kits")
    op.drop_index(op.f("ix_bike_families_brand_name"), table_name="bike_families")
    op.drop_table("bike_families")
    # ### end Alembic commands ###
