"""initial

Revision ID: b8641691a825
Revises:
Create Date: 2026-02-12 12:41:17.357259

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8641691a825"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bike_definitions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("model_name", sa.String(), nullable=False),
        sa.Column("category", sa.String(), nullable=False),
        sa.Column("year_start", sa.Integer(), nullable=True),
        sa.Column("year_end", sa.Integer(), nullable=True),
        sa.Column("material", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("brand_name", "model_name", name="_brand_model_uc"),
    )
    op.create_index(op.f("ix_bike_definitions_brand_name"), "bike_definitions", ["brand_name"], unique=False)
    op.create_table(
        "geometry_specs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("definition_id", sa.Integer(), nullable=False),
        sa.Column("size_label", sa.String(), nullable=False),
        sa.Column("stack_mm", sa.Integer(), nullable=False),
        sa.Column("reach_mm", sa.Integer(), nullable=False),
        sa.Column("top_tube_effective_mm", sa.Integer(), nullable=True),
        sa.Column("seat_tube_length_mm", sa.Integer(), nullable=True),
        sa.Column("head_tube_length_mm", sa.Integer(), nullable=True),
        sa.Column("head_tube_angle", sa.Float(), nullable=False),
        sa.Column("seat_tube_angle", sa.Float(), nullable=False),
        sa.Column("chainstay_length_mm", sa.Integer(), nullable=False),
        sa.Column("wheelbase_mm", sa.Integer(), nullable=False),
        sa.Column("bb_drop_mm", sa.Integer(), nullable=False),
        sa.Column("fork_offset_mm", sa.Integer(), nullable=True),
        sa.Column("trail_mm", sa.Integer(), nullable=True),
        sa.Column("standover_height_mm", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["definition_id"], ["bike_definitions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_geometry_specs_reach_mm"), "geometry_specs", ["reach_mm"], unique=False)
    op.create_index(op.f("ix_geometry_specs_stack_mm"), "geometry_specs", ["stack_mm"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geometry_specs_stack_mm"), table_name="geometry_specs")
    op.drop_index(op.f("ix_geometry_specs_reach_mm"), table_name="geometry_specs")
    op.drop_table("geometry_specs")
    op.drop_index(op.f("ix_bike_definitions_brand_name"), table_name="bike_definitions")
    op.drop_table("bike_definitions")
    # ### end Alembic commands ###
