"""align_orm_structure_with_cascades

Revision ID: d30f598bc1c0
Revises: b3b1fc3d67ef
Create Date: 2026-02-10 11:31:41.162738

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d30f598bc1c0"
down_revision: str | Sequence[str] | None = "b3b1fc3d67ef"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("bike_products")
    op.drop_table("build_kits")
    op.alter_column(
        "bike_families",
        "brand_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "bike_families",
        "family_name",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=50),
        existing_nullable=False,
    )
    op.alter_column(
        "bike_families",
        "category",
        existing_type=sa.VARCHAR(length=255),
        type_=sa.String(length=30),
        existing_nullable=False,
    )
    op.alter_column(
        "frame_definitions",
        "name",
        existing_type=sa.VARCHAR(length=512),
        type_=sa.String(length=100),
        existing_nullable=False,
    )
    op.alter_column(
        "frame_definitions",
        "material",
        existing_type=sa.VARCHAR(length=1024),
        type_=sa.String(length=30),
        existing_nullable=True,
    )
    op.drop_constraint(op.f("_def_size_uc"), "geometry_specs", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        op.f("_def_size_uc"), "geometry_specs", ["definition_id", "size_label"], postgresql_nulls_not_distinct=False
    )
    op.alter_column(
        "frame_definitions",
        "material",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=1024),
        existing_nullable=True,
    )
    op.alter_column(
        "frame_definitions",
        "name",
        existing_type=sa.String(length=100),
        type_=sa.VARCHAR(length=512),
        existing_nullable=False,
    )
    op.alter_column(
        "bike_families",
        "category",
        existing_type=sa.String(length=30),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "bike_families",
        "family_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.alter_column(
        "bike_families",
        "brand_name",
        existing_type=sa.String(length=50),
        type_=sa.VARCHAR(length=255),
        existing_nullable=False,
    )
    op.create_table(
        "build_kits",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column("groupset", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("wheelset", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("cockpit", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("tires", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("build_kits_pkey")),
    )
    op.create_table(
        "bike_products",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("sku", sa.VARCHAR(), autoincrement=False, nullable=False),
        sa.Column(
            "colors",
            postgresql.JSON(astext_type=sa.Text()),
            server_default=sa.text("'[]'::json"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("geometry_spec_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("build_kit_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("source_url", sa.VARCHAR(length=1024), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["build_kit_id"], ["build_kits.id"], name=op.f("bike_products_build_kit_id_fkey"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["geometry_spec_id"],
            ["geometry_specs.id"],
            name=op.f("bike_products_geometry_spec_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("bike_products_pkey")),
        sa.UniqueConstraint(
            "geometry_spec_id",
            "build_kit_id",
            name=op.f("_geo_bk_uc"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "sku", name=op.f("bike_products_sku_key"), postgresql_include=[], postgresql_nulls_not_distinct=False
        ),
    )
    # ### end Alembic commands ###
